package org.example

class Fields {
    fun getFieldDetails(): Map<Int, FieldDetail> {
        return mapOf(
            1 to FieldDetail("Bitmap", FieldDefinition("BINARY", 16)),
            2 to FieldDetail("Primary Account Number (PAN)", FieldDefinition("NUMERIC", 19)),
            3 to FieldDetail("Processing Code", FieldDefinition("NUMERIC", 6)),
            4 to FieldDetail("Amount, Transaction", FieldDefinition("NUMERIC", 12)),
            5 to FieldDetail("Amount, Settlement", FieldDefinition("NUMERIC", 12)),
            6 to FieldDetail("Amount, Cardholder Billing", FieldDefinition("NUMERIC", 12)),
            7 to FieldDetail("Transmission Date and Time", FieldDefinition("NUMERIC", 10)),
            8 to FieldDetail("Amount, Cardholder Billing Fee", FieldDefinition("NUMERIC", 8)),
            9 to FieldDetail("Conversion Rate, Settlement", FieldDefinition("NUMERIC", 8)),
            10 to FieldDetail("Conversion Rate, Cardholder Billing", FieldDefinition("NUMERIC", 8)),
            11 to FieldDetail("System Trace Audit Number (STAN)", FieldDefinition("NUMERIC", 6)),
            12 to FieldDetail("Local Transaction Time (hhmmss)", FieldDefinition("NUMERIC", 6)),
            13 to FieldDetail("Local Transaction Date (MMDD)", FieldDefinition("NUMERIC", 4)),
            14 to FieldDetail("Expiration Date (YYMM)", FieldDefinition("NUMERIC", 4)),
            15 to FieldDetail("Settlement Date", FieldDefinition("NUMERIC", 4)),
            16 to FieldDetail("Currency Conversion Date", FieldDefinition("NUMERIC", 4)),
            17 to FieldDetail("Capture Date", FieldDefinition("NUMERIC", 4)),
            18 to FieldDetail("Merchant Type, or Merchant Category Code", FieldDefinition("NUMERIC", 4)),
            19 to FieldDetail("Acquiring Institution Country Code", FieldDefinition("NUMERIC", 3)),
            20 to FieldDetail("PAN Extended Country Code", FieldDefinition("NUMERIC", 3)),
            21 to FieldDetail("Forwarding Institution Country Code", FieldDefinition("NUMERIC", 3)),
            22 to FieldDetail("Point of Service Entry Mode", FieldDefinition("NUMERIC", 3)),
            23 to FieldDetail("Application PAN Sequence Number", FieldDefinition("NUMERIC", 3)),
            24 to FieldDetail("Function Code or NII", FieldDefinition("NUMERIC", 3)),
            25 to FieldDetail("Point of Service Condition Code", FieldDefinition("NUMERIC", 2)),
            26 to FieldDetail("Point of Service Capture Code", FieldDefinition("NUMERIC", 2)),
            27 to FieldDetail("Authorizing Identification Response Length", FieldDefinition("NUMERIC", 1)),
            28 to FieldDetail("Amount, Transaction Fee", FieldDefinition("NUMERIC", 8)),
            29 to FieldDetail("Amount, Settlement Fee", FieldDefinition("NUMERIC", 8)),
            30 to FieldDetail("Amount, Transaction Processing Fee", FieldDefinition("NUMERIC", 8)),
            31 to FieldDetail("Amount, Settlement Processing Fee", FieldDefinition("NUMERIC", 8)),
            32 to FieldDetail("Acquiring Institution Identification Code", FieldDefinition("LLVAR", 11)),
            33 to FieldDetail("Forwarding Institution Identification Code", FieldDefinition("LLVAR", 11)),
            34 to FieldDetail("Primary Account Number, Extended", FieldDefinition("LLVAR", 28)),
            35 to FieldDetail("Track 2 Data", FieldDefinition("LLVAR", 37)),
            36 to FieldDetail("Track 3 Data", FieldDefinition("LLLVAR", 104)),
            37 to FieldDetail("Retrieval Reference Number", FieldDefinition("ALPHA", 12)),
            38 to FieldDetail("Authorization Identification Response", FieldDefinition("ALPHA", 6)),
            39 to FieldDetail("Response Code", FieldDefinition("ALPHA", 2)),
            40 to FieldDetail("Service Restriction Code", FieldDefinition("ALPHA", 3)),
            41 to FieldDetail("Card Acceptor Terminal Identification", FieldDefinition("ALPHANUMERIC", 16)),
            42 to FieldDetail("Card Acceptor Identification Code", FieldDefinition("ALPHANUMERIC", 15)),
            43 to FieldDetail("Card Acceptor Name/Location", FieldDefinition("ALPHANUMERIC", 40)),
            44 to FieldDetail("Additional Response Data", FieldDefinition("LLVAR", 25)),
            45 to FieldDetail("Track 1 Data", FieldDefinition("LLVAR", 76)),
            46 to FieldDetail("Additional Data (ISO)", FieldDefinition("LLLVAR", 999)),
            47 to FieldDetail("Additional Data (National)", FieldDefinition("LLLVAR", 999)),
            48 to FieldDetail("Additional Data (Private)", FieldDefinition("LLLVAR", 999)),
            49 to FieldDetail("Currency Code, Transaction", FieldDefinition("ALPHA", 3)),
            50 to FieldDetail("Currency Code, Settlement", FieldDefinition("ALPHA", 3)),
            51 to FieldDetail("Currency Code, Cardholder Billing", FieldDefinition("ALPHA", 3)),
            52 to FieldDetail("Personal Identification Number Data", FieldDefinition("BINARY", 64)),
            53 to FieldDetail("Security Related Control Information", FieldDefinition("NUMERIC", 16)),
            54 to FieldDetail("Additional Amounts", FieldDefinition("LLLVAR", 120)),
            55 to FieldDetail("ICC Data - EMV Multiple Tags", FieldDefinition("LLLVAR", 999)),
            56 to FieldDetail("Reserved (ISO)", FieldDefinition("LLLVAR", 999)),
            57 to FieldDetail("Reserved (National)", FieldDefinition("LLLVAR", 999)),
            58 to FieldDetail("Reserved", FieldDefinition("LLLVAR", 999)),
            59 to FieldDetail("Reserved", FieldDefinition("LLLVAR", 999)),
            60 to FieldDetail("Reserved (National)", FieldDefinition("LLLVAR", 999)),
            61 to FieldDetail("Reserved (Private)", FieldDefinition("LLLVAR", 999)),
            62 to FieldDetail("Reserved (Private)", FieldDefinition("LLLVAR", 999)),
            63 to FieldDetail("Reserved (Private)", FieldDefinition("LLLVAR", 999)),
            64 to FieldDetail("Message Authentication Code (MAC)", FieldDefinition("BINARY", 64)),
            65 to FieldDetail("Extended Bitmap Indicator", FieldDefinition("BINARY", 1)),
            66 to FieldDetail("Settlement Code", FieldDefinition("NUMERIC", 1)),
            67 to FieldDetail("Extended Payment Code", FieldDefinition("NUMERIC", 2)),
            68 to FieldDetail("Receiving Institution Country Code", FieldDefinition("NUMERIC", 3)),
            69 to FieldDetail("Settlement Institution Country Code", FieldDefinition("NUMERIC", 3)),
            70 to FieldDetail("Network Management Information Code", FieldDefinition("NUMERIC", 3)),
            71 to FieldDetail("Message Number", FieldDefinition("NUMERIC", 4)),
            72 to FieldDetail("Last Message Number", FieldDefinition("NUMERIC", 4)),
            73 to FieldDetail("Action Date (YYMMDD)", FieldDefinition("NUMERIC", 6)),
            74 to FieldDetail("Number of Credits", FieldDefinition("NUMERIC", 10)),
            75 to FieldDetail("Credits, Reversal Number", FieldDefinition("NUMERIC", 10)),
            76 to FieldDetail("Number of Debits", FieldDefinition("NUMERIC", 10)),
            77 to FieldDetail("Debits, Reversal Number", FieldDefinition("NUMERIC", 10)),
            78 to FieldDetail("Transfer Number", FieldDefinition("NUMERIC", 10)),
            79 to FieldDetail("Transfer, Reversal Number", FieldDefinition("NUMERIC", 10)),
            80 to FieldDetail("Number of Inquiries", FieldDefinition("NUMERIC", 10)),
            81 to FieldDetail("Number of Authorizations", FieldDefinition("NUMERIC", 10)),
            82 to FieldDetail("Credits, Processing Fee Amount", FieldDefinition("NUMERIC", 12)),
            83 to FieldDetail("Credits, Transaction Fee Amount", FieldDefinition("NUMERIC", 12)),
            84 to FieldDetail("Debits, Processing Fee Amount", FieldDefinition("NUMERIC", 12)),
            85 to FieldDetail("Debits, Transaction Fee Amount", FieldDefinition("NUMERIC", 12)),
            86 to FieldDetail("Total Amount of Credits", FieldDefinition("NUMERIC", 16)),
            87 to FieldDetail("Credits, Reversal Amount", FieldDefinition("NUMERIC", 16)),
            88 to FieldDetail("Total Amount of Debits", FieldDefinition("NUMERIC", 16)),
            89 to FieldDetail("Debits, Reversal Amount", FieldDefinition("NUMERIC", 16)),
            90 to FieldDetail("Original Data Elements", FieldDefinition("NUMERIC", 42)),
            91 to FieldDetail("File Update Code", FieldDefinition("ALPHA", 1)),
            92 to FieldDetail("File Security Code", FieldDefinition("ALPHA", 2)),
            93 to FieldDetail("Response Indicator", FieldDefinition("ALPHA", 5)),
            94 to FieldDetail("Service Indicator", FieldDefinition("ALPHA", 7)),
            95 to FieldDetail("Replacement Amounts", FieldDefinition("NUMERIC", 42)),
            96 to FieldDetail("Message Security Code", FieldDefinition("BINARY", 64)),
            97 to FieldDetail("Net Settlement Amount", FieldDefinition("NUMERIC", 16)),
            98 to FieldDetail("Payee", FieldDefinition("ALPHANUMERIC", 25)),
            99 to FieldDetail("Settlement Institution Identification Code", FieldDefinition("LLVAR", 11)),
            100 to FieldDetail("Receiving Institution Identification Code", FieldDefinition("LLVAR", 11)),
            101 to FieldDetail("File Name", FieldDefinition("LLLVAR", 17)),
            102 to FieldDetail("Account Identification 1", FieldDefinition("LLVAR", 28)),
            103 to FieldDetail("Account Identification 2", FieldDefinition("LLVAR", 28)),
            104 to FieldDetail("Transaction Description", FieldDefinition("LLLVAR", 100)),
            105 to FieldDetail("Reserved for ISO Use", FieldDefinition("LLLVAR", 999)),
            106 to FieldDetail("Reserved for ISO Use", FieldDefinition("LLLVAR", 999)),
            120 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            121 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            122 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            123 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            124 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            125 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999)),
            126 to FieldDetail("Reserved for Private Use", FieldDefinition("LLLVAR", 999))
        )
    }

    fun hexToBinary(hex: String): String {
        return hex.map { Character.digit(it, 16).toString(2).padStart(4, '0') }.joinToString("")
    }

    data class FieldDetail(val label: String, val definition: FieldDefinition)
    data class FieldDefinition(val type: String, val length: Int)
}